# Example configuration file (config.yaml) for video creation pipeline

# List of tasks to be executed for the directory
# Each task has a set of converters that are applied in sequence

fps: &default_fps 60 # all values: 23.976, 24, 25, 29.97, 30, 50, 60
# info : https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#moviepy.video.VideoClip.VideoClip.write_videofile
video_quality: &quality
  fps: *default_fps
  codec: "libx264" # all values: h264, hevc, mpeg4, vp8, vp9, libx264, libx265, libxvid, rawvideo
  preset: "medium" # all values: ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow
fade: &fade 0.2
image_duration: &image_duration 10
image_height: &image_height 1024  
# all values: COLORMAP_AUTUMN, COLORMAP_BONE, COLORMAP_JET, COLORMAP_WINTER, COLORMAP_RAINBOW, COLORMAP_OCEAN, COLORMAP_SUMMER, 
# COLORMAP_SPRING, COLORMAP_COOL, COLORMAP_HSV, COLORMAP_PINK, COLORMAP_HOT, COLORMAP_PARULA, COLORMAP_MAGMA, COLORMAP_INFERNO, 
# COLORMAP_PLASMA, COLORMAP_VIRIDIS, COLORMAP_CIVIDIS, COLORMAP_TWILIGHT, COLORMAP_TWILIGHT_SHIFTED, COLORMAP_TURBO, COLORMAP_DEEPGREEN
# https://learnopencv.com/applycolormap-for-pseudocoloring-in-opencv-c-python/
colormap: &colormap "COLORMAP_JET"
crop: &crop
  # start_time: 0
  # end_time: 60  # End of the audio

tasks:
  # - name: "Create Full Length Video"
  #   converters:
  #     - type: "AudioReaderConverter"
  #       config: *crop
  #     - type: "SlideshowCreatorConverter"
  #       config:
  #         cover:
  #           name: cover
  #           duration: 10
  #         slideshow:
  #           height: *image_height  # Height of the images to be unified
  #           duration: *image_duration
  #         transition:
  #           fade_in: *fade  # Fade-in duration in seconds
  #           fade_out: *fade  # Fade-out duration in seconds
  #           fade_in_first_image: false
  #     - type: "ImageOverlayConverter"
  #       config:
  #         image:
  #           path: "static/animated2.gif"
  #           resize: 1
  #           position:
  #             x: "left" # values: left, center, right
  #             y: "bottom" # values: top, center, bottom
  #         timing:
  #           start_time: -33
  #           duration: 30
  #     - type: "SplitConverter"
  #       config:
  #         parts: 6
  #     - type: "TwoSpotsVisualizationConverter"
  #       config:
  #         visualization:
  #           fps: *default_fps
  #           # OpenCV  https://learnopencv.com/applycolormap-for-pseudocoloring-in-opencv-c-python/
  #           colormap: *colormap
  #     - type: "JoinConverter"
  #       config: *quality
  #         # fps: *default_fps
  #         # codec: "png" # all values: h264, hevc, mpeg4, vp8, vp9, libx264, libx265, libxvid, rawvideo, png
  #         # preset: "medium" # all values: ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow
  #     - type: "AudioReaderConverter"
  #       config: *crop
  #     - type: "VideoExportConverter"
  #       config:
  #         quality: *quality

  # - name: "Create YouTube Short"
  #   converters:
  #     - type: "AudioReaderConverter"
  #       config:
  #         start_time: 9
  #         end_time: 64  # Duration of 30 seconds
  #     - type: "SlideshowCreatorConverter"
  #       config:
  #         slideshow:
  #           height: *image_height  # Height for YouTube Short format
  #           width: 600
  #           ratio: crop # or resize 
  #         transition:
  #           fade_in: *fade  
  #           fade_out: *fade
  #     - type: "ImageOverlayConverter"
  #       config:
  #         image:
  #           path: "static/animated2.gif"
  #           resize: 1
  #           position:
  #             x: "right" # values: left, center, right
  #             y: "top" # values: top, center, bottom
  #         timing:
  #           start_time: -9
  #           duration: 7            
  #     - type: "TwoSpotsVisualizationConverter"
  #       config:
  #         visualization:
  #           fps: *default_fps
  #           # OpenCV  https://learnopencv.com/applycolormap-for-pseudocoloring-in-opencv-c-python/
  #           colormap: *colormap
  #     - type: "VideoExportConverter"
  #       config:
  #         output_file: "short_output.mp4"
  #         quality:
  #           fps: *default_fps
  #           codec: "libx264"
  #           quality_preset: "medium"

  - name: "Create TikTok"
    converters:
      - type: "AudioReaderConverter"
        config: *crop
      - type: "SlideshowCreatorConverter"
        config:
          slideshow:
            height: *image_height  # Height for YouTube Short format
            width: 800
            ratio: crop # or resize 
          transition:
            fade_in: *fade  
            fade_out: *fade
      - type: "VideoExportConverter"
        config:
          output_file: "tiktok.mp4"
          quality:
            fps: *default_fps
            codec: "libx264"
            quality_preset: "medium"

