# Example configuration file (config.yaml) for video creation pipeline

# List of tasks to be executed for the directory
# Each task has a set of converters that are applied in sequence

fps: &default_fps 24

tasks:
  - name: "Create Full Length Video"
    converters:
      - type: "AudioReaderConverter"
        config:
          start_time: 0
          end_time: 60  # End of the audio
      - type: "SlideshowCreatorConverter"
        config:
          slideshow:
            height: 512  # Height of the images to be unified
            duration: 10
          transition:
            fade_in: 0.5  # Fade-in duration in seconds
            fade_out: 0.5  # Fade-out duration in seconds
            fade_in_first_image: false
      # - type: "TextOverlayConverter"
      #   config:
      #     text: "Welcome to Our Video"
      #     position:
      #       x: "50%"  # Position in percentage for horizontal centering
      #       y: "90%"  # Position in percentage for vertical placement at the bottom
      #     font:
      #       name: "Arial"
      #       size: 24
      #       color: "white"
      #     contour:
      #       color: "black"
      #       size: 2
      #     transition:
      #       fade_in: 0.5
      #       fade_out: 0.5
      - type: "ImageOverlayConverter"
        config:
          image:
            path: "static/animated2.gif"
            resize: 1
            position:
              x: "left"  # Position in pixels (e.g., '10pt') or percentage (e.g., '10%')
              y: "bottom"  # Position in pixels (e.g., '20pt') or percentage (e.g., '20%')
          timing:
            start_time: -32  
            # duration: 10   
      # - type: "SplitConverter"
      #   config:
      #     parts: 3
      # - type: "TwoSpotsVisualizationConverter"
      #   config:
      #     visualization:
      #       fps: *default_fps
      #       colormap: "COLORMAP_JET"  # OpenCV  https://learnopencv.com/applycolormap-for-pseudocoloring-in-opencv-c-python/
      # - type: "JoinConverter"
      # - type: "AudioReaderConverter"
      #   config:
      #     start_time: 0
      #     end_time: null  # End of the audio, searches for mp3 in directory
      - type: "VideoExportConverter"
        config:
          export:
            output_path: "output.mp4"
            fps: *default_fps
            codec: "libx264"
            quality_preset: "medium"

  # - name: "Create YouTube Short"
  #   converters:
  #     - type: "AudioReaderConverter"
  #       config:
  #         start_time: 30
  #         end_time: 60  # Duration of 30 seconds
  #     - type: "SlideshowCreatorConverter"
  #       config:
  #         slideshow:
  #           height: 1080  # Height for YouTube Short format
  #         transition:
  #           fade_in: 0.5
  #           fade_out: 0.5
  #     - type: "TextOverlayConverter"
  #       config:
  #         text: "Enjoy this Short Clip!"
  #         position:
  #           x: "50%"  # Position in percentage for horizontal centering
  #           y: "50%"  # Position in percentage for vertical centering
  #         font:
  #           name: "Arial"
  #           size: 32
  #           color: "yellow"
  #         contour:
  #           color: "black"
  #           size: 2
  #         transition:
  #           fade_in: 0.5
  #           fade_out: 0.5
  #     - type: "VideoExportConverter"
  #       config:
  #         export:
  #           output_path: "short_output.mp4"
  #           fps: 30
  #           codec: "libx264"
  #           quality_preset: "high"
