# Example configuration file (config.yaml) for video creation pipeline

# List of tasks to be executed for the directory
# Each task has a set of converters that are applied in sequence

fps: &default_fps 60 # all values: 23.976, 24, 25, 29.97, 30, 50, 60
video_quality: &quality
  fps: *default_fps
  codec: "libx264" # all values: h264, hevc, mpeg4, vp8, vp9, libx264, libx265, libxvid, rawvideo
  preset: "medium" # all values: ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow
fade: &fade 0.2
image_duration: &image_duration 10
crop: &crop
image_height: &image_height 1024  
  # start_time: 0
  # end_time: 50  # End of the audio

tasks:
  - name: "Create Full Length Video"
    converters:
      - type: "AudioReaderConverter"
        config: *crop
      - type: "SlideshowCreatorConverter"
        config:
          slideshow:
            height: *image_height  # Height of the images to be unified
            duration: *image_duration
          transition:
            fade_in: *fade  # Fade-in duration in seconds
            fade_out: *fade  # Fade-out duration in seconds
            fade_in_first_image: false
      # - type: "TextOverlayConverter"
      # config:
      #     text: "Welcome to Our Video"
      #     position:
      #       x: "50%"  # Position in percentage for horizontal centering
      #       y: "90%"  # Position in percentage for vertical placement at the bottom
      #     font:
      #       name: "Arial"
      #       size: 24
      #       color: "white"
      #     contour:
      #       color: "black"
      #       size: 2
      #     transition:
      #       fade_in: 0.5
      #       fade_out: 0.5
      # - type: "ImageOverlayConverter"
      #   config:
      #     image:
      #       path: "static/animated2.gif"
      #       resize: 0.5
      #       position:
      #         x: "left"  # Position in pixels (e.g., '10pt') or percentage (e.g., '10%')
      #         y: "bottom"  # Position in pixels (e.g., '20pt') or percentage (e.g., '20%')
      #     timing:
      #       start_time: -32
      #       duration: 31
      - type: "SplitConverter"
        config:
          parts: 5
      # - type: "ChannelBarsVisualizer"
      #   config:
      #     audio:
      #       sample_rate: 48000
      #     visualization:
      #       fps: *default_fps
      #       bar_height_scale: 1.0
      #       bar_width: 20
      #       spacing: 10
      #       colormap: "COLORMAP_JET"  # OpenCV  https://learnopencv.com/applycolormap-for-pseudocoloring-in-opencv-c-python/
      - type: "TwoSpotsVisualizationConverter"
        config:
          audio:
            sample_rate: 10000
          visualization:
            fps: *default_fps
            # OpenCV  https://learnopencv.com/applycolormap-for-pseudocoloring-in-opencv-c-python/
            colormap: "COLORMAP_JET" # all values: COLORMAP_AUTUMN, COLORMAP_BONE, COLORMAP_JET, COLORMAP_WINTER, COLORMAP_RAINBOW, COLORMAP_OCEAN, COLORMAP_SUMMER, COLORMAP_SPRING, COLORMAP_COOL, COLORMAP_HSV, COLORMAP_PINK, COLORMAP_HOT, COLORMAP_PARULA, COLORMAP_MAGMA, COLORMAP_INFERNO, COLORMAP_PLASMA, COLORMAP_VIRIDIS, COLORMAP_CIVIDIS, COLORMAP_TWILIGHT, COLORMAP_TWILIGHT_SHIFTED, COLORMAP_TURBO, COLORMAP_DEEPGREEN
      - type: "JoinConverter"
        config:
          fps: *default_fps
          codec: "png" # all values: h264, hevc, mpeg4, vp8, vp9, libx264, libx265, libxvid, rawvideo, png
          preset: "medium" # all values: ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow
      - type: "AudioReaderConverter"
        config: *crop
      - type: "VideoExportConverter"
        config:
          quality: *quality

  # - name: "Create YouTube Short"
  #   converters:
  #     - type: "AudioReaderConverter"
  #       config:
  #         start_time: 0
  #         end_time: 59  # Duration of 30 seconds
  #     - type: "SlideshowCreatorConverter"
  #       config:
  #         slideshow:
  #           height: *image_height  # Height for YouTube Short format
  #           width: 638
  #           ratio: crop # or resize 
  #         transition:
  #           fade_in: *fade  
  #           fade_out: *fade
  # #     - type: "TextOverlayConverter"
  # #       config:
  # #         text: "Enjoy this Short Clip!"
  # #         position:
  # #           x: "50%"  # Position in percentage for horizontal centering
  # #           y: "50%"  # Position in percentage for vertical centering
  # #         font:
  # #           name: "Arial"
  # #           size: 32
  # #           color: "yellow"
  # #         contour:
  # #           color: "black"
  # #           size: 2
  # #         transition:
  # #           fade_in: 0.5
  # #           fade_out: 0.5
  #     - type: "VideoExportConverter"
  #       config:
  #         output_file: "short_output.mp4"
  #         quality:
  #           fps: *default_fps
  #           codec: "libx264"
  #           quality_preset: "medium"
